server:
  port: 8102
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: user
    password: letmein
    jpa:
      hibernate:
        ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.common.serialization.StringSerializer
      value-serializer: org.spring.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.magret.dto.OrderConfirmation
application:
  config:
    customer-url: http://localhost:8222/api/v1/customer
    product-url: http://localhost:8222/api/v1/products
    payment-url: http://localhost:8222/api/v1/payments