server:
  port: 8101
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: user
    password: letmein
    jpa:
      hibernate:
        ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}